
micronaut:
  server:
    port: 8083
  export:
    prometheus:
      enabled: true
      step: PT1M
      descriptions: true
endpoints:
  prometheus:
    sensitive: false


mongodb:
  uri: mongodb://localhost:27017/table-db

redis:
  uri: redis://localhost:6379
  ssl: true
  timeout: 30s
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  caches:
    products:
      expire-after-write: 60s

flyway:
  datasources:
    default:
      enabled: true


kafka:
  bootstrap:
    servers: localhost:9092

  topic:
    start: start
    notify: notify

  consumer:
    group-id: table-group
    auto-offset-reset: latest

logger:
  levels:
    org.apache.kafka: OFF






